server:
    port: ${PORT:8080}
    session:
        timeout: 600

spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        password: 1234
        url: jdbc:mysql://127.0.0.1:3306/imooc-demo?useUnicode=true&characterEncoding=UTF-8&useSSL=false
        username: root
    session:
        store-type: redis
#    redis:
#      host: localhost
#      port:

# 关闭身份验证
#security:
#  basic:
#    enabled: false
imooc:
    security:
        browser:
            alwaysRemember: false
            loginType: ${loginType:Redirect}
            passedUrls: /index.html,/user/regist,/social/user,/demo-binding.html,/imooc-binding.html,/imooc-logout-success.html
            session:
                maxSessionsPreventsLogin: false
                maximumSessions: 1
            signUpUrl: /demo-signUp.html
            logoutSuccessPage: /demo-logout-success.html
        code:
            image:
                length: 6
                url: /user
                width: 150
        social:
            filterProcessesUrl: /qqLogin
            qq:
                app-id: 100550231
                app-secret: 69b6ab57b22f3c2fe6a6149274e3295e
                providerId: callback.do
            weixin:
                app-id: wxd99431bbff8305a0
                app-secret: 60f78681d063590a469f1b297feff3c4
                providerId: weixin
logging:
    level:
        root: info

